### ISSUE TITLE
[DOC] aux_computation_time_init.gms missing or docstring needs update

### ISSUE THREAD

**Issue by ojdo** [iiasa/gams_stub#1]
The docstring in file `model/includes/aux_computation_time.gms` says

> requires **aux_computation_time_init.gms**

Either that file is missing, or this docstring can go.

**Comment by gidden** [comment]
This is in @danielhuppmann's wheel house, mind taking a look?

**Comment by danielhuppmann** [comment]
Thanks for pointing this out - I deleted that comment...
